# https://taskfile.dev

version: '3'

vars:
  APPNAME: app
env:
  CC: clang

tasks:
  default:
    cmds:
      - task: clean
      - task: run
  run:
    cmds:
      - ${CC} -g3 -O0 -o {{.APPNAME}} main.c
      - ./{{.APPNAME}}
  clean:
    cmds:
      - rm -f {{.APPNAME}}
