# https://taskfile.dev

version: '3'

vars:
  APP: app

tasks:
  default:
    cmds:
      - rm -f {{.APP}} out.txt
      - gcc -std=gnu11 -Wall -Wextra -g3 -O0 -o {{.APP}} {{.APP}}.c
      - ./{{.APP}} 1 # unlinkあり
      - cmd: ls out.txt
        ignore_error: true
      - ./{{.APP}} 0  # unlinkなし
      - ls out.txt
